# FB Page Locators
UKThemes = "//a[text() = '"
EndElement = "']"
listNeedToCheckPlaceholder = "//div[@class = 'placeholder']"
inputLastName = "//input[@name = 'lastname']"
inputFirstName = "//input[@name = 'firstname']"
inputEmail = "//input[@name = 'reg_email__']"
inputEmailConfirmation = "//input[@name = 'reg_email_confirmation__']"
inputPassword = "//input[@name = 'reg_passwd__']"
selectDay = "//select[@name = 'birthday_day']"
selectMonth = "//select[@name = 'birthday_month']"
selectYear = "//select[@name = 'birthday_year']"
listGenderRadio = "//input[@type = 'radio']"
registerButton = "//button[@type = 'submit']"
needMoreInfomation = "//span[text()= 'Chúng tôi cần thêm thông tin']"
iconBirthdayHelp = "//a[@id = 'birthday-help']"
iconGenderHelp = "//a[@id = 'gender-help']"
contentTooltip = "//div[@class = '_9hzn']"
